/* eslint-disable @typescript-eslint/no-explicit-any */

// Lazy import jsPDF to avoid bundling issues if not installed
export async function exportSessionReport({
  session,
  sessionStats,
}: {
  session: any | null;
  sessionStats: any | null;
}) {
  try {
    const jsPDFMod: any = await import("jspdf");
    const jsPDF = jsPDFMod.default || jsPDFMod;
    const doc = new jsPDF({ unit: "pt", format: "a4" });

    const marginX = 48; // 0.67in
    const pageWidth = doc.internal.pageSize.getWidth();
    const centerX = pageWidth / 2;
    let y = 56;

    const line = (yPos: number) => {
      doc.setDrawColor(220);
      doc.line(marginX, yPos, 595 - marginX, yPos);
    };

    const text = (
      t: string,
      x: number,
      yPos: number,
      size = 12,
      bold = false
    ) => {
      doc.setFont("Helvetica", bold ? "bold" : "normal");
      doc.setFontSize(size);
      doc.text(t, x, yPos);
    };

    const textCenter = (t: string, yPos: number, size = 12, bold = false) => {
      doc.setFont("Helvetica", bold ? "bold" : "normal");
      doc.setFontSize(size);
      doc.text(t, centerX, yPos, { align: "center" });
    };

    // Logo (optional)
    try {
      const resp = await fetch("/pdflogo.png");
      if (resp.ok) {
        const blob = await resp.blob();
        const dataUrl: string = await new Promise((resolve) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result as string);
          reader.readAsDataURL(blob);
        });
        const logoW = 48;
        const logoH = 48;
        const logoX = centerX - logoW / 2;
        const logoY = 32;
        doc.addImage(dataUrl, "PNG", logoX, logoY, logoW, logoH);
        y = logoY + logoH + 20;
      }
    } catch {
      // ignore logo errors; continue without image
    }

    // Header
    textCenter("Session Summary Report", y, 20, true);
    y += 26;
    const sessionName = session?.name || sessionStats?.session?.name || "";
    textCenter(`Session: ${sessionName}`, y);
    y += 18;
    line(y);
    y += 18;

    // Overview
    text("Overview", marginX, y, 14, true);
    y += 18;
    const ov = sessionStats?.overview || {};
    const perf = sessionStats?.performance || {};
    const avg = Math.round(Number(perf?.averageScore ?? 0));
    const completion = Math.round(Number(ov?.completionRate ?? 0));

    const overviewRows = [
      ["Total Jurors", String(ov?.totalJurors ?? 0)],
      ["Total Responses", String(ov?.totalResponses ?? 0)],
      ["Total Assessments", String(ov?.totalAssessments ?? 0)],
      ["Average Suitability", `${avg}%`],
      ["Completion Rate", `${completion}%`],
    ];

    overviewRows.forEach(([k, v]) => {
      text(k, marginX, y);
      text(v, 300, y, 12, true);
      y += 18;
    });

    y += 6;
    line(y);
    y += 18;

    // Performance Breakdown
    text("Performance Breakdown", marginX, y, 14, true);
    y += 18;
    const high = Number(perf?.highPerformers ?? 0);
    const mid = Number(perf?.mediumPerformers ?? 0);
    const low = Number(perf?.lowPerformers ?? 0);
    const bullets = [
      `Ideal for the Case — Score above 80%: ${high} Jurors`,
      `Neutral to the Case — Score between 60% and 79%: ${mid} Jurors`,
      `Recommended to Strike — Score below 60%: ${low} Jurors`,
    ];
    bullets.forEach((b) => {
      text(`• ${b}`, marginX, y);
      y += 18;
    });

    y += 6;
    text("Methodology", marginX, y, 14, true);
    y += 18;
    const wrapText = (t: string, x: number, maxWidth: number) => {
      const parts = doc.splitTextToSize(t, maxWidth);
      parts.forEach((p: string) => {
        text(p, x, y);
        y += 16;
      });
    };

    wrapText(
      "Suitability is calculated from AI assessments of juror responses and aggregated across questions.",
      marginX,
      595 - marginX * 2
    );
    wrapText(
      "Thresholds: Above 80% — Considered ideal for the case; 60% to 79% — Considered neutral to the case; Below 60% — Recommended to strike.",
      marginX,
      595 - marginX * 2
    );
    wrapText(
      "Scores are directional indicators and judgment.",
      marginX,
      595 - marginX * 2
    );

    y += 6;
    text("Notes", marginX, y, 14, true);
    y += 18;
    wrapText(
      "This section is intentionally left for attorney notes and observations captured during voir dire or strategy meetings.",
      marginX,
      595 - marginX * 2
    );

    y += 6;
    line(Math.min(y, 780));
    const issued = new Date().toLocaleString();
    text("Generated by Elite Jury", marginX, 820);
    text(`Issued Date: ${issued}`, 595 - marginX - 200, 820);

    const fileName = `session-report-${Date.now()}.pdf`;
    doc.save(fileName);
  } catch (err) {
    // Fallback: instruct to install dependency
    alert(
      "PDF export requires 'jspdf'. Please run: npm i jspdf --save, then retry."
    );
    console.error("Failed to export PDF:", err);
  }
}
